platform :ios, '15.6'

target 'RxSample' do
  use_frameworks!

  pod 'Cause-Logic-Effect'
	pod 'RxEnumKit'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if target.name == 'RxSwift' and config.name == 'Debug'
                config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['-D', 'TRACE_RESOURCES']
            end
        end
    end
end
